### ISSUE TITLE
Name of `.apkg` file is something from the relativ path, not the deck_name. Should it be fixed? 

### ISSUE THREAD

**Issue by J0inas** [J0inas/CardDown#35]
Possible fix with `os.rename()`.

**Comment by CallMeCrazYN** [comment]
the labeling of the .apkg file could work like this:

- if the user provides a save_path argument like /dir/filename.apkg this naming should be used
- if the user did not provide a save_path and the current dir will be used as a save directory but the deck_name is the filename
- if nothing is provided the path argument will be used for naming

**Comment by J0inas** [comment]
I think I already implemted it similar to that.
