### ISSUE TITLE
Try to find a way for handling images embedded as URLs

### ISSUE THREAD

**Issue by CallMeCrazYN** [J0inas/CardDown#36]

**Comment by J0inas** [comment]
is that possible with simple html?
or
maybe another point for a rework of the `replace_tag`-Function?

**Comment by CallMeCrazYN** [comment]
with html it would be possible. we can search for the <img> tag and then extract the url from that and temporarily save the image. 

the problem "difficult/annoying" part would be, that we would need to adjust the link to the image on the card

**Comment by CallMeCrazYN** [comment]
nvm. apparently genanki or anki can handle the links to images already.
another possibility could be the markdown python module
so images from links work out of the box, which is pretty neat :)
